#include "VulkanBarrier.h"
#include "Utils.h"
#include "../command/VulkanCommand.h"

namespace engine {
void vulkanBarrier(struct VulkanCommand* cmd, enum ExecutionBarrierType barrierType) {
    VkMemoryBarrier2 memoryBarrier = {};
    memoryBarrier.sType            = VK_STRUCTURE_TYPE_MEMORY_BARRIER_2;

    switch (barrierType) {
        case GRAPHICS_TO_COMPUTE:
            // Wait for color attachment writes to be finished before compute shader reads.
            memoryBarrier.srcStageMask  = VK_PIPELINE_STAGE_2_COLOR_ATTACHMENT_OUTPUT_BIT;
            memoryBarrier.srcAccessMask = VK_ACCESS_2_COLOR_ATTACHMENT_WRITE_BIT;
            memoryBarrier.dstStageMask  = VK_PIPELINE_STAGE_2_COMPUTE_SHADER_BIT;
            memoryBarrier.dstAccessMask = VK_ACCESS_2_SHADER_READ_BIT;
            break;

        case COMPUTE_TO_GRAPHICS:
            // Wait for compute shader writes to be finished before fragment shader reads.
            memoryBarrier.srcStageMask  = VK_PIPELINE_STAGE_2_COMPUTE_SHADER_BIT;
            memoryBarrier.srcAccessMask = VK_ACCESS_2_SHADER_WRITE_BIT;
            memoryBarrier.dstStageMask  = VK_PIPELINE_STAGE_2_FRAGMENT_SHADER_BIT;
            memoryBarrier.dstAccessMask = VK_ACCESS_2_SHADER_READ_BIT;
            break;

        case COMPUTE_TO_COMPUTE:
            // Wait for compute shader writes to be finished before subsequent compute shader reads.
            memoryBarrier.srcStageMask  = VK_PIPELINE_STAGE_2_COMPUTE_SHADER_BIT;
            memoryBarrier.srcAccessMask = VK_ACCESS_2_SHADER_WRITE_BIT;
            memoryBarrier.dstStageMask  = VK_PIPELINE_STAGE_2_COMPUTE_SHADER_BIT;
            memoryBarrier.dstAccessMask = VK_ACCESS_2_SHADER_READ_BIT;
            break;

        case TRANSFER_TO_SHADER:
            // Wait for transfer writes to be finished before any shader reads.
            memoryBarrier.srcStageMask  = VK_PIPELINE_STAGE_2_TRANSFER_BIT;
            memoryBarrier.srcAccessMask = VK_ACCESS_2_TRANSFER_WRITE_BIT;
            memoryBarrier.dstStageMask  = VK_PIPELINE_STAGE_2_COMPUTE_SHADER_BIT | VK_PIPELINE_STAGE_2_FRAGMENT_SHADER_BIT;
            memoryBarrier.dstAccessMask = VK_ACCESS_2_SHADER_READ_BIT;
            break;

        case COMPUTE_TO_TRANSFER:
            // Wait for compute shader writes to be finished before transfer reads.
            memoryBarrier.srcStageMask  = VK_PIPELINE_STAGE_2_COMPUTE_SHADER_BIT;
            memoryBarrier.srcAccessMask = VK_ACCESS_2_SHADER_WRITE_BIT;
            memoryBarrier.dstStageMask  = VK_PIPELINE_STAGE_2_TRANSFER_BIT;
            memoryBarrier.dstAccessMask = VK_ACCESS_2_TRANSFER_READ_BIT;
            break;

        case GRAPHICS_TO_TRANSFER:
            // Wait for color attachment writes to be finished before transfer reads.
            memoryBarrier.srcStageMask  = VK_PIPELINE_STAGE_2_COLOR_ATTACHMENT_OUTPUT_BIT;
            memoryBarrier.srcAccessMask = VK_ACCESS_2_COLOR_ATTACHMENT_WRITE_BIT;
            memoryBarrier.dstStageMask  = VK_PIPELINE_STAGE_2_TRANSFER_BIT;
            memoryBarrier.dstAccessMask = VK_ACCESS_2_TRANSFER_READ_BIT;
            break;

        case COMPUTE_TO_INDIRECT_DRAW:
            // Wait for compute shader writes (to an indirect buffer) to be finished before the draw command reads it.
            memoryBarrier.srcStageMask  = VK_PIPELINE_STAGE_2_COMPUTE_SHADER_BIT;
            memoryBarrier.srcAccessMask = VK_ACCESS_2_SHADER_WRITE_BIT;
            memoryBarrier.dstStageMask  = VK_PIPELINE_STAGE_2_DRAW_INDIRECT_BIT;
            memoryBarrier.dstAccessMask = VK_ACCESS_2_INDIRECT_COMMAND_READ_BIT;
            break;

        case GRAPHICS_TO_GRAPHICS:
            // Use Case: Post-processing, deferred rendering (G-Buffer -> Lighting pass).
            // Syncs color attachment writes with subsequent fragment shader reads.
            memoryBarrier.srcStageMask  = VK_PIPELINE_STAGE_2_COLOR_ATTACHMENT_OUTPUT_BIT;
            memoryBarrier.srcAccessMask = VK_ACCESS_2_COLOR_ATTACHMENT_WRITE_BIT;
            memoryBarrier.dstStageMask  = VK_PIPELINE_STAGE_2_FRAGMENT_SHADER_BIT;
            memoryBarrier.dstAccessMask = VK_ACCESS_2_SHADER_SAMPLED_READ_BIT;
            break;

        case SHADER_TO_TRANSFER:
            // Use Case: Saving a texture generated by a compute or graphics pass to a file.
            // Syncs any shader write with a subsequent transfer read (e.g., vkCmdCopyImageToBuffer).
            memoryBarrier.srcStageMask  = VK_PIPELINE_STAGE_2_ALL_GRAPHICS_BIT | VK_PIPELINE_STAGE_2_COMPUTE_SHADER_BIT;
            memoryBarrier.srcAccessMask = VK_ACCESS_2_SHADER_WRITE_BIT;
            memoryBarrier.dstStageMask  = VK_PIPELINE_STAGE_2_TRANSFER_BIT;
            memoryBarrier.dstAccessMask = VK_ACCESS_2_TRANSFER_READ_BIT;
            break;

        case COMPUTE_TO_INDIRECT_COMMAND:
            // Use Case: GPU-driven rendering where a compute shader determines draw call parameters.
            // Syncs compute shader writes to an indirect buffer with the draw call that reads it.
            memoryBarrier.srcStageMask  = VK_PIPELINE_STAGE_2_COMPUTE_SHADER_BIT;
            memoryBarrier.srcAccessMask = VK_ACCESS_2_SHADER_WRITE_BIT;
            memoryBarrier.dstStageMask  = VK_PIPELINE_STAGE_2_DRAW_INDIRECT_BIT;
            memoryBarrier.dstAccessMask = VK_ACCESS_2_INDIRECT_COMMAND_READ_BIT;
            break;

        case COMPUTE_TO_VERTEX_INPUT:
            // Use Case: Procedural geometry or particle simulation where a compute shader generates vertex data.
            // Syncs compute writes to a buffer with the vertex input stage that reads it.
            memoryBarrier.srcStageMask  = VK_PIPELINE_STAGE_2_COMPUTE_SHADER_BIT;
            memoryBarrier.srcAccessMask = VK_ACCESS_2_SHADER_WRITE_BIT;
            memoryBarrier.dstStageMask  = VK_PIPELINE_STAGE_2_VERTEX_ATTRIBUTE_INPUT_BIT;
            memoryBarrier.dstAccessMask = VK_ACCESS_2_VERTEX_ATTRIBUTE_READ_BIT;
            break;

        case TRANSFER_TO_VERTEX_INPUT:
            // Use Case: Copy data into index/vertex buffers then use them to render.
            memoryBarrier.srcStageMask  = VK_PIPELINE_STAGE_2_TRANSFER_BIT;
            memoryBarrier.srcAccessMask = VK_ACCESS_2_TRANSFER_WRITE_BIT;
            memoryBarrier.dstStageMask  = VK_PIPELINE_STAGE_2_VERTEX_ATTRIBUTE_INPUT_BIT | VK_PIPELINE_STAGE_2_INDEX_INPUT_BIT;
            memoryBarrier.dstAccessMask = VK_ACCESS_2_VERTEX_ATTRIBUTE_READ_BIT | VK_ACCESS_2_INDEX_READ_BIT;
            break;

        case DEVICE_WRITE_TO_HOST_READ:
            // Use Case: Reading back data to the CPU (screenshots, simulation results).
            // Makes any writes on the GPU visible to the host.
            // Note: This is for resources in HOST_VISIBLE memory.
            memoryBarrier.srcStageMask  = VK_PIPELINE_STAGE_2_ALL_COMMANDS_BIT;  // Any GPU work
            memoryBarrier.srcAccessMask = VK_ACCESS_2_MEMORY_WRITE_BIT;          // Any write
            memoryBarrier.dstStageMask  = VK_PIPELINE_STAGE_2_HOST_BIT;
            memoryBarrier.dstAccessMask = VK_ACCESS_2_HOST_READ_BIT;
            break;

        case HOST_WRITE_TO_DEVICE_READ:
            // Use Case: Using data just uploaded from the CPU via a mapped buffer.
            // Makes host writes visible to the GPU before it reads the data.
            memoryBarrier.srcStageMask  = VK_PIPELINE_STAGE_2_HOST_BIT;
            memoryBarrier.srcAccessMask = VK_ACCESS_2_HOST_WRITE_BIT;
            memoryBarrier.dstStageMask  = VK_PIPELINE_STAGE_2_ALL_COMMANDS_BIT;  // Any GPU work
            memoryBarrier.dstAccessMask = VK_ACCESS_2_MEMORY_READ_BIT;           // Any read
            break;

        default:
            // Or assert, log an error, etc.
            utils::terminate("Unsupported barrier type!");
    }

    VkDependencyInfo dependencyInfo   = {};
    dependencyInfo.sType              = VK_STRUCTURE_TYPE_DEPENDENCY_INFO;
    dependencyInfo.memoryBarrierCount = 1;
    dependencyInfo.pMemoryBarriers    = &memoryBarrier;

    vkCmdPipelineBarrier2(cmd->cmd, &dependencyInfo);
}
}  // namespace engine
